backend:
  name: git-gateway
  branch: main
  repo: bfuller7141/Sun-City-Mechanical-Test
  accept_roles:
    - admin
    - editor
  api_root: https://gitlab.com/api/v4

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "locations"
    label: "Locations"
    folder: "src/content/cities"
    create: true
    extension: "md"
    slug: "{{city}}"
    fields:
      - label: "City"
        name: "city"
        widget: "string"
      - label: "About"
        name: "about"
        widget: "markdown"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Slug"
        name: "slug"
        widget: "string"

  - name: "testimonials"
    label: "Testimonials"
    folder: "src/content/testimonials"
    create: true
    extension: "md"
    slug: "{{name}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
      - label: "Testimonial"
        name: "testimonial"
        widget: "markdown"
      - label: "Rating"
        name: "rating"
        widget: "number"
        min: 1
        max: 5
        step: 1
      - label: "Slug"
        name: "slug"
        widget: "string"

  - name: "air-quality"
    label: "Air Quality"
    folder: "src/content/air-quality"
    create: true
    extension: "md"
    slug: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Icon"
        name: "icon"
        widget: "image"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Content"
        name: "content"
        widget: "markdown"
      - label: "Question 1"
        name: "question1"
        widget: "string"
      - label: "Answer 1"
        name: "answer1"
        widget: "string"
      - label: "Question 2"
        name: "question2"
        widget: "string"
      - label: "Answer 2"
        name: "answer2"
        widget: "string"
      - label: "Question 3"
        name: "question3"
        widget: "string"
      - label: "Answer 3"
        name: "answer3"
        widget: "string"

  - name: "heating"
    label: "Heating"
    folder: "src/content/heating"
    create: true
    extension: "md"
    slug: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Icon"
        name: "icon"
        widget: "image"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Content"
        name: "content"
        widget: "markdown"
      - label: "Question 1"
        name: "question1"
        widget: "string"
      - label: "Answer 1"
        name: "answer1"
        widget: "string"
      - label: "Question 2"
        name: "question2"
        widget: "string"
      - label: "Answer 2"
        name: "answer2"
        widget: "string"
      - label: "Question 3"
        name: "question3"
        widget: "string"
      - label: "Answer 3"
        name: "answer3"
        widget: "string"

  - name: "cooling"
    label: "Cooling"
    folder: "src/content/cooling"
    create: true
    extension: "md"
    slug: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Icon"
        name: "icon"
        widget: "image"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Content"
        name: "content"
        widget: "markdown"
      - label: "Question 1"
        name: "question1"
        widget: "string"
      - label: "Answer 1"
        name: "answer1"
        widget: "string"
      - label: "Question 2"
        name: "question2"
        widget: "string"
      - label: "Answer 2"
        name: "answer2"
        widget: "string"
      - label: "Question 3"
        name: "question3"
        widget: "string"
      - label: "Answer 3"
        name: "answer3"
        widget: "string"
